Bump Go version
This bumps the version of Go to satisfy a dependency:

```
[build 7/9] RUN go get -u

2.174 go: go.mod requires go >= 1.25.1 (running go 1.24.3;
GOTOOLCHAIN=local)

ERROR: process "/bin/sh -c go get -u" did not complete successfully:
exit code: 1
```